
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '334B263010E9494CBBE5A1FE880C2C17'
    
_lr_action_items = {'MINUS':([1,2,3,4,10,11,12,13,14,15,],[6,-7,-6,-3,6,-2,-1,-5,-4,-8,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-7,-6,-3,15,-2,-1,-5,-4,-8,]),'NUM':([0,5,6,7,8,9,],[2,2,2,2,2,2,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[7,-7,-6,-3,7,-2,-1,-5,-4,-8,]),'DIVIDE':([2,3,4,11,12,13,14,15,],[-7,-6,8,8,8,-5,-4,-8,]),'TIMES':([2,3,4,11,12,13,14,15,],[-7,-6,9,9,9,-5,-4,-8,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-7,-6,-3,-2,-1,-5,-4,-8,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,5,],[1,10,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),'term':([0,5,6,7,],[4,4,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr','parser.py',30),
  ('expr -> expr MINUS term','expr',3,'p_expr','parser.py',31),
  ('expr -> term','expr',1,'p_expr_term','parser.py',40),
  ('term -> term TIMES factor','term',3,'p_term','parser.py',46),
  ('term -> term DIVIDE factor','term',3,'p_term','parser.py',47),
  ('term -> factor','term',1,'p_term_factor','parser.py',56),
  ('factor -> NUM','factor',1,'p_factor','parser.py',62),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_group','parser.py',68),
]
